//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGreenSpace.LangResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoGreenSpace.LangResources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string buttonLogin {
            get {
                return ResourceManager.GetString("buttonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string buttonRegister {
            get {
                return ResourceManager.GetString("buttonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar foto.
        /// </summary>
        internal static string buttonUpload {
            get {
                return ResourceManager.GetString("buttonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Has olvidado la contraseña?.
        /// </summary>
        internal static string labelForgottenPassword {
            get {
                return ResourceManager.GetString("labelForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        internal static string labelMail {
            get {
                return ResourceManager.GetString("labelMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string labelRegister {
            get {
                return ResourceManager.GetString("labelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir Contraseña.
        /// </summary>
        internal static string labelRepeatPassword {
            get {
                return ResourceManager.GetString("labelRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string labelUser {
            get {
                return ResourceManager.GetString("labelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes una cuenta?.
        /// </summary>
        internal static string lblQuestion {
            get {
                return ResourceManager.GetString("lblQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Todavía no tienes una cuenta?.
        /// </summary>
        internal static string lblQuestionRegister {
            get {
                return ResourceManager.GetString("lblQuestionRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string linkLogin {
            get {
                return ResourceManager.GetString("linkLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string linkRegister
        {
            get
            {
                return ResourceManager.GetString("linkRegister", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Enviar código de verificación.
        /// </summary>
        internal static string buttonSend
        {
            get
            {
                return ResourceManager.GetString("buttonSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a MENU.
        /// </summary>
        internal static string labelMenu
        {
            get
            {
                return ResourceManager.GetString("labelMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Taquilla.
        /// </summary>
        internal static string buttonTicketOffice
        {
            get
            {
                return ResourceManager.GetString("buttonTicketOffice", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Revisar Tickets.
        /// </summary>
        internal static string buttonReviewTickets
        {
            get
            {
                return ResourceManager.GetString("buttonReviewTickets", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Reseñas.
        /// </summary>
        internal static string buttonReviews
        {
            get
            {
                return ResourceManager.GetString("buttonReviews", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ecribir reseña.
        /// </summary>
        internal static string buttonWriteReview
        {
            get
            {
                return ResourceManager.GetString("buttonWriteReview", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string buttonUser
        {
            get
            {
                return ResourceManager.GetString("buttonUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string buttonConfiguration
        {
            get
            {
                return ResourceManager.GetString("buttonConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ESTRENOS - PELÍCULAS MAYO 2024.
        /// </summary>
        internal static string labelTitle
        {
            get
            {
                return ResourceManager.GetString("labelTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PRÓXIMOS ESTRENOS - PELÍCULAS JUNIO 2024.
        /// </summary>
        internal static string labelNextTitle
        {
            get
            {
                return ResourceManager.GetString("labelNextTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tú nombre de usuario, recibirás en tú correo...
        /// </summary>
        internal static string rtbInfo
        {
            get
            {
                return ResourceManager.GetString("rtbInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Enviar enlace
        /// </summary>
        internal static string buttonLink
        {
            get
            {
                return ResourceManager.GetString("buttonLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PELÍCULAS
        /// </summary>
        internal static string labelFilm
        {
            get
            {
                return ResourceManager.GetString("labelFilm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a TIPO DE SALA
        /// </summary>
        internal static string labelTypeHall
        {
            get
            {
                return ResourceManager.GetString("labelTypeHall", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE
        /// </summary>
        internal static string labelName
        {
            get
            {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a HORARIO
        /// </summary>
        internal static string labelSchedule
        {
            get
            {
                return ResourceManager.GetString("labelSchedule", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a DURACIÓN
        /// </summary>
        internal static string labelDuration
        {
            get
            {
                return ResourceManager.GetString("labelDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a TICKETS:
        /// </summary>
        internal static string labelTickets
        {
            get
            {
                return ResourceManager.GetString("labelTickets", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a DESCUENTOS:
        /// </summary>
        internal static string labelDiscounts
        {
            get
            {
                return ResourceManager.GetString("labelDiscounts", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a DESCUENTO:
        /// </summary>
        internal static string labelDiscount
        {
            get
            {
                return ResourceManager.GetString("labelDiscount", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL:
        /// </summary>
        internal static string labelTotal
        {
            get
            {
                return ResourceManager.GetString("labelTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL APLICADO:
        /// </summary>
        internal static string labelTotalApplied
        {
            get
            {
                return ResourceManager.GetString("labelTotalApplied", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a BUTACAS
        /// </summary>
        internal static string labelSeating
        {
            get
            {
                return ResourceManager.GetString("labelSeating", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a SINOPSIS
        /// </summary>
        internal static string labelSynopsis
        {
            get
            {
                return ResourceManager.GetString("labelSynopsis", resourceCulture);
            }
        }
    }
}
