//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGreenSpace.LangResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoGreenSpace.LangResources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string buttonLogin {
            get {
                return ResourceManager.GetString("buttonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string buttonRegister {
            get {
                return ResourceManager.GetString("buttonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar foto.
        /// </summary>
        internal static string buttonUpload {
            get {
                return ResourceManager.GetString("buttonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Has olvidado la contraseña?.
        /// </summary>
        internal static string labelForgottenPassword {
            get {
                return ResourceManager.GetString("labelForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        internal static string labelMail {
            get {
                return ResourceManager.GetString("labelMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string labelRegister {
            get {
                return ResourceManager.GetString("labelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir Contraseña.
        /// </summary>
        internal static string labelRepeatPassword {
            get {
                return ResourceManager.GetString("labelRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string labelUser {
            get {
                return ResourceManager.GetString("labelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes una cuenta?.
        /// </summary>
        internal static string lblQuestion {
            get {
                return ResourceManager.GetString("lblQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Todavía no tienes una cuenta?.
        /// </summary>
        internal static string lblQuestionRegister {
            get {
                return ResourceManager.GetString("lblQuestionRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string linkLogin {
            get {
                return ResourceManager.GetString("linkLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string linkRegister
        {
            get
            {
                return ResourceManager.GetString("linkRegister", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Enviar código de verificación.
        /// </summary>
        internal static string buttonSend
        {
            get
            {
                return ResourceManager.GetString("buttonSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a MENU.
        /// </summary>
        internal static string labelMenu
        {
            get
            {
                return ResourceManager.GetString("labelMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Taquilla.
        /// </summary>
        internal static string buttonTicketOffice
        {
            get
            {
                return ResourceManager.GetString("buttonTicketOffice", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Revisar Tickets.
        /// </summary>
        internal static string buttonReviewTickets
        {
            get
            {
                return ResourceManager.GetString("buttonReviewTickets", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Reseñas.
        /// </summary>
        internal static string buttonReviews
        {
            get
            {
                return ResourceManager.GetString("buttonReviews", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ecribir reseña.
        /// </summary>
        internal static string buttonWriteReview
        {
            get
            {
                return ResourceManager.GetString("buttonWriteReview", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string buttonUser
        {
            get
            {
                return ResourceManager.GetString("buttonUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string buttonConfiguration
        {
            get
            {
                return ResourceManager.GetString("buttonConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ESTRENOS - PELÍCULAS MAYO 2024.
        /// </summary>
        internal static string labelTitle
        {
            get
            {
                return ResourceManager.GetString("labelTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PRÓXIMOS ESTRENOS - PELÍCULAS JUNIO 2024.
        /// </summary>
        internal static string labelNextTitle
        {
            get
            {
                return ResourceManager.GetString("labelNextTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tú nombre de usuario, recibirás en tú correo...
        /// </summary>
        internal static string rtbInfo
        {
            get
            {
                return ResourceManager.GetString("rtbInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Enviar enlace
        /// </summary>
        internal static string buttonLink
        {
            get
            {
                return ResourceManager.GetString("buttonLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PELÍCULAS
        /// </summary>
        internal static string labelFilm
        {
            get
            {
                return ResourceManager.GetString("labelFilm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a TIPO DE SALA
        /// </summary>
        internal static string labelTypeHall
        {
            get
            {
                return ResourceManager.GetString("labelTypeHall", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE
        /// </summary>
        internal static string labelName
        {
            get
            {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a HORARIO
        /// </summary>
        internal static string labelSchedule
        {
            get
            {
                return ResourceManager.GetString("labelSchedule", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a DURACIÓN
        /// </summary>
        internal static string labelDuration
        {
            get
            {
                return ResourceManager.GetString("labelDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a TICKETS:
        /// </summary>
        internal static string labelTickets
        {
            get
            {
                return ResourceManager.GetString("labelTickets", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a DESCUENTOS:
        /// </summary>
        internal static string labelDiscounts
        {
            get
            {
                return ResourceManager.GetString("labelDiscounts", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a DESCUENTO:
        /// </summary>
        internal static string labelDiscount
        {
            get
            {
                return ResourceManager.GetString("labelDiscount", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL:
        /// </summary>
        internal static string labelTotal
        {
            get
            {
                return ResourceManager.GetString("labelTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL APLICADO:
        /// </summary>
        internal static string labelTotalApplied
        {
            get
            {
                return ResourceManager.GetString("labelTotalApplied", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a BUTACAS
        /// </summary>
        internal static string labelSeating
        {
            get
            {
                return ResourceManager.GetString("labelSeating", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a SINOPSIS
        /// </summary>
        internal static string labelSynopsis
        {
            get
            {
                return ResourceManager.GetString("labelSynopsis", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Estrellas
        /// </summary>
        internal static string comboStars
        {
            get
            {
                return ResourceManager.GetString("comboStars", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Películas
        /// </summary>
        internal static string comboMovies
        {
            get
            {
                return ResourceManager.GetString("comboMovies", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar por
        /// </summary>
        internal static string comboOrder
        {
            get
            {
                return ResourceManager.GetString("comboOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Reestablecer
        /// </summary>
        internal static string buttonReset
        {
            get
            {
                return ResourceManager.GetString("buttonReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Escribe aquí tu reseña...
        /// </summary>
        internal static string labelReviewTitle
        {
            get
            {
                return ResourceManager.GetString("labelReviewTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Envíar
        /// </summary>
        internal static string buttonSendReview
        {
            get
            {
                return ResourceManager.GetString("buttonSendReview", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión
        /// </summary>
        internal static string labelLogOut
        {
            get
            {
                return ResourceManager.GetString("labelLogOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Miembro desde
        /// </summary>
        internal static string labelJoinApp
        {
            get
            {
                return ResourceManager.GetString("labelJoinApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tickets actuales
        /// </summary>
        internal static string labelActualTickets
        {
            get
            {
                return ResourceManager.GetString("labelActualTickets", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tickets pasados
        /// </summary>
        internal static string labelPastTickets
        {
            get
            {
                return ResourceManager.GetString("labelPastTickets", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        internal static string buttonAdmin
        {
            get
            {
                return ResourceManager.GetString("buttonAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta
        /// </summary>
        internal static string buttonAccount
        {
            get
            {
                return ResourceManager.GetString("buttonAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario
        /// </summary>
        internal static string labelNameUser
        {
            get
            {
                return ResourceManager.GetString("labelNameUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Nombre
        /// </summary>
        internal static string buttonChangeName
        {
            get
            {
                return ResourceManager.GetString("buttonChangeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar foto
        /// </summary>
        internal static string buttonChangePhoto
        {
            get
            {
                return ResourceManager.GetString("buttonChangePhoto", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta asociada de correo
        /// </summary>
        internal static string labelMailAssociated
        {
            get
            {
                return ResourceManager.GetString("labelMailAssociated", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña
        /// </summary>
        internal static string buttonChangePassword
        {
            get
            {
                return ResourceManager.GetString("buttonChangePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar cuenta
        /// </summary>
        internal static string buttonDeleteAccount
        {
            get
            {
                return ResourceManager.GetString("buttonDeleteAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Salir
        /// </summary>
        internal static string buttonExit
        {
            get
            {
                return ResourceManager.GetString("buttonExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Elige el tipo de modo:
        /// </summary>
        internal static string grpSwitch
        {
            get
            {
                return ResourceManager.GetString("grpSwitch", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar idioma:
        /// </summary>
        internal static string labelChangeLanguage
        {
            get
            {
                return ResourceManager.GetString("labelChangeLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Predet.
        /// </summary>
        internal static string buttonDefault
        {
            get
            {
                return ResourceManager.GetString("buttonDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Películas
        /// </summary>
        internal static string lblFilm
        {
            get
            {
                return ResourceManager.GetString("lblFilm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Sinopsis
        /// </summary>
        internal static string lblSynopsis
        {
            get
            {
                return ResourceManager.GetString("lblSynopsis", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Duración
        /// </summary>
        internal static string lblDuration
        {
            get
            {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Precio
        /// </summary>
        internal static string lblPrice
        {
            get
            {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Años mínimos
        /// </summary>
        internal static string lblMinAge
        {
            get
            {
                return ResourceManager.GetString("lblMinAge", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cargar imagen
        /// </summary>
        internal static string btnUpload
        {
            get
            {
                return ResourceManager.GetString("btnUpload", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Géneros
        /// </summary>
        internal static string lblGenre
        {
            get
            {
                return ResourceManager.GetString("lblGenre", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Próximo estreno
        /// </summary>
        internal static string chbPremiering
        {
            get
            {
                return ResourceManager.GetString("chbPremiering", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Insertar
        /// </summary>
        internal static string btnInsert
        {
            get
            {
                return ResourceManager.GetString("btnInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Acceso modificaciones
        /// </summary>
        internal static string btnModifyFrm
        {
            get
            {
                return ResourceManager.GetString("btnModifyFrm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Acceso inserciones
        /// </summary>
        internal static string btnInsertFrm
        {
            get
            {
                return ResourceManager.GetString("btnInsertFrm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Acceso eliminaciones
        /// </summary>
        internal static string btnDeleteFrm
        {
            get
            {
                return ResourceManager.GetString("btnDeleteFrm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Próximos extrenos
        /// </summary>
        internal static string chbNextPremiering
        {
            get
            {
                return ResourceManager.GetString("chbNextPremiering", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a AActualizar
        /// </summary>
        internal static string btnUpdateFilm
        {
            get
            {
                return ResourceManager.GetString("btnUpdateFilm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar
        /// </summary>
        internal static string btnDeleteFilm
        {
            get
            {
                return ResourceManager.GetString("btnDeleteFilm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Modificar películas
        /// </summary>
        internal static string groupBoxModify
        {
            get
            {
                return ResourceManager.GetString("groupBoxModify", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar películas
        /// </summary>
        internal static string groupBoxDelete
        {
            get
            {
                return ResourceManager.GetString("groupBoxDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Acceso sesiones
        /// </summary>
        internal static string btnAccessSessions
        {
            get
            {
                return ResourceManager.GetString("btnAccessSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Acceso sesiones
        /// </summary>
        internal static string labelNewUsername
        {
            get
            {
                return ResourceManager.GetString("labelNewUsername", resourceCulture);
            }
        }
    }
}
